/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RushRouteImport } from './routes/rush'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonDayRouteImport } from './routes/lesson.$day'
import { Route as DevotionalIdRouteImport } from './routes/devotional.$id'

const RushRoute = RushRouteImport.update({
  id: '/rush',
  path: '/rush',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonDayRoute = LessonDayRouteImport.update({
  id: '/lesson/$day',
  path: '/lesson/$day',
  getParentRoute: () => rootRouteImport,
} as any)
const DevotionalIdRoute = DevotionalIdRouteImport.update({
  id: '/devotional/$id',
  path: '/devotional/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rush': typeof RushRoute
  '/devotional/$id': typeof DevotionalIdRoute
  '/lesson/$day': typeof LessonDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rush': typeof RushRoute
  '/devotional/$id': typeof DevotionalIdRoute
  '/lesson/$day': typeof LessonDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rush': typeof RushRoute
  '/devotional/$id': typeof DevotionalIdRoute
  '/lesson/$day': typeof LessonDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rush' | '/devotional/$id' | '/lesson/$day'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rush' | '/devotional/$id' | '/lesson/$day'
  id: '__root__' | '/' | '/rush' | '/devotional/$id' | '/lesson/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RushRoute: typeof RushRoute
  DevotionalIdRoute: typeof DevotionalIdRoute
  LessonDayRoute: typeof LessonDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rush': {
      id: '/rush'
      path: '/rush'
      fullPath: '/rush'
      preLoaderRoute: typeof RushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$day': {
      id: '/lesson/$day'
      path: '/lesson/$day'
      fullPath: '/lesson/$day'
      preLoaderRoute: typeof LessonDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devotional/$id': {
      id: '/devotional/$id'
      path: '/devotional/$id'
      fullPath: '/devotional/$id'
      preLoaderRoute: typeof DevotionalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RushRoute: RushRoute,
  DevotionalIdRoute: DevotionalIdRoute,
  LessonDayRoute: LessonDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
